#!/bin/bash

if [ 'vyattacfg' != $(id -ng) ]; then
 exec sg vyattacfg -c "$0 $@"
fi
run=/opt/vyatta/sbin/vyatta-cfg-cmd-wrapper


$run begin
$run set system package repository stretch components 'main contrib non-free' 
$run set system package repository stretch distribution stretch
$run set system package repository stretch url http://http.us.debian.org/debian
$run commit
$run end

sudo apt update
sudo apt install -y git

cd ~
sudo git clone https://github.com/ewyand/wireguard.git
cd ~/wireguard
sudo chmod 755 *
