#!/bin/bash

if [ 'vyattacfg' != $(id -ng) ]; then
 exec sg vyattacfg -c "$0 $@"
fi

read -p "Did you Download the file? " -n 1 -r
echo    # (optional) move to a new line
if [[ ! $REPLY =~ ^[Yy]$ ]]
then
    exit 1
fi

#read -p "Public IP of this router: " endpoint
#echo "Here is th IP you entered $endpoint "
echo "First one"


url='https://github.com/WireGuard/wireguard-vyatta-ubnt/releases'
html=$( curl -# -L "${url}" 2> '/dev/null' )

module=$(
  <<< "${html}" \
  grep -P -o -e '(?<=<li>Module <strong>)(.*?)(?=<\/strong><\/li>)' |
  head -n 1
)

tools=$(
  <<< "${html}" \
  grep -P -o -e '(?<=<li>Tools <strong>)(.*?)(?=<\/strong><\/li>)' |
  head -n 1
)

printf '%s\n' "Module: ${module}" "Tools: ${tools}"




echo "End of File 123"
