#!/bin/bash

if [ 'vyattacfg' != $(id -ng) ]; then
 exec sg vyattacfg -c "$0 $@"
fi

run=/opt/vyatta/sbin/vyatta-cfg-cmd-wrapper

sudo rm /config/auth/wg.key
sudo rm /config/auth/wg.public

$run begin

$run delete interfaces wireguard
$run delete firewall name WAN_LOCAL rule 120

$run commit
$run save
$run end

sudo dpkg --remove wireguard
sudo apt remove qrencode -y
sudo apt autoremove -y
sudo rm *.deb
sudo rm /config/scripts/*.conf
sudo rm /config/scripts/*.peer
sudo rm /config/scripts/addvpn
sudo rm /config/scripts/nextip.txt
cd ~ && rm -rf wireguard
