#!/bin/bash

if [ 'vyattacfg' != $(id -ng) ]; then
 exec sg vyattacfg -c "$0 $@"
fi
run=/opt/vyatta/sbin/vyatta-cfg-cmd-wrapper

curl -OL https://github.com/WireGuard/wireguard-vyatta-ubnt/releases/download/1.0.20210606-1/e300-v2-v1.0.20210606-v1.0.20210424.deb

sudo dpkg -i *.deb


wg genkey | tee /config/auth/wg.key | wg pubkey >  /config/auth/wg.public


routerpubkey=`cat /config/auth/wg.public`

read -p "Public IP of this router: " endpoint
read -p "List local IP you want access over VPN (seperate with comma's): " allowedips
#echo "Here is th IP you entered $endpoint "
#echo " This is the local public key: $routerpubkey "





$run begin
$run set interfaces wireguard wg0 address 10.255.255.1/24
$run set interfaces wireguard wg0 listen-port 51820
$run set interfaces wireguard wg0 route-allowed-ips true
$run set interfaces wireguard wg0 private-key /config/auth/wg.key
$run set firewall name WAN_LOCAL rule 120 action accept
$run set firewall name WAN_LOCAL rule 120 protocol udp
$run set firewall name WAN_LOCAL rule 120 description 'WireGuard'
$run set firewall name WAN_LOCAL rule 120 destination port 51820
$run set system package repository stretch components 'main contrib non-free' 
$run set system package repository stretch distribution stretch
$run set system package repository stretch url http://http.us.debian.org/debian
$run commit
$run end


sudo apt-get update && sudo apt-get install qrencode -y

$run begin
$run delete system package
$run commit
$run end


touch /config/scripts/nextip.txt
cat >> /config/scripts/nextip.txt << EOF
2
EOF

sed "s/routerpubkey=CHANGEME/routerpubkey=$routerpubkey/g" -i ~/wireguard/addvpn
#sed "s/routerip=CHANGEME/routerip=$routerip/g" -i ~/wireguard/addvpn
sed "s/endpoint=CHANGEME/endpoint=$endpoint/g" -i ~/wireguard/addvpn
sed "s/allowedips=CHANGEME/allowedips=$allowedips/g" -i ~/wireguard/addvpn
