#!/bin/bash

read -p "Public IP of this router: " endpoint

if [ 'vyattacfg' != $(id -ng) ]; then
 exec sg vyattacfg -c "$0 $@"
fi

run=/opt/vyatta/sbin/vyatta-cfg-cmd-wrapper


wg genkey | tee /config/auth/wg.key | wg pubkey >  /config/auth/wg.public


$run begin
$run set interfaces wireguard wg0 address 10.255.255.1/24
$run set interfaces wireguard wg0 listen-port 51820
$run set interfaces wireguard wg0 route-allowed-ips true
$run set interfaces wireguard wg0 private-key /config/auth/wg.key
$run set firewall name WAN_LOCAL rule 120 action accept
$run set firewall name WAN_LOCAL rule 120 protocol udp
$run set firewall name WAN_LOCAL rule 120 description 'WireGuard'
$run set firewall name WAN_LOCAL rule 120 destination port 51820
$run set system package repository stretch components 'main contrib non-free' 
$run set system package repository stretch distribution stretch
$run set system package repository stretch url http://http.us.debian.org/debian
$run commit
$run end


sudo apt-get update && sudo apt-get install qrencode -y

$run begin
$run delete system package
$run commit
$run end


touch /config/scripts/nextip.txt
cat >> /config/scripts/nextip.txt << EOF
2
EOF
